apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      containers:
      - image: datadog/agent:6.2.0
        imagePullPolicy: Always
        name: datadog-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
        env:
          - name: DD_API_KEY
            value: XXXXXXXXXXXXXXXXXXXXXXX
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_KUBELET_TLS_VERIFY
            value: "true"
          - name: KUBERNETES_LEADER_ELECTION
            value: "true"
          - name: KUBERNETES_LEADER_CANDIDATE
            value: "true"
          - name: KUBERNETES_NAMESPACE_NAME_REGEX
            value: "'.*'"
          - name: KUBERNETES
            value: "yes"
          - name: DD_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_KUBELETS_CLIENT_CRT
            value: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: agent-config
            mountPath: /etc/datadog-agent/datadog.yaml
            subPath: datadog.yaml
        livenessProbe:
          exec:
            command:
            - ./probe.sh
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - name: agent-config
          configMap:
            name: datadog-agent-config
      securityContext: {}
      serviceAccount: datadog
      serviceAccountName: datadog
