apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: datadog
subjects:
- kind: ServiceAccount
  name: datadog
  namespace: %%NAMESPACE%%
roleRef:
  kind: ClusterRole
  name: datadog
  apiGroup: rbac.authorization.k8s.io
